-- MySQL Script generated by MySQL Workbench
-- Fri Mar 30 23:14:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AdSearchDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AdSearchDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AdSearchDB` DEFAULT CHARACTER SET utf8 ;
USE `AdSearchDB` ;

-- -----------------------------------------------------
-- Table `AdSearchDB`.`campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdSearchDB`.`campaign` (
  `campaign_id` INT NOT NULL AUTO_INCREMENT,
  `budget` DOUBLE NULL,
  PRIMARY KEY (`campaign_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AdSearchDB`.`ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdSearchDB`.`ad` (
  `ad_id` INT NOT NULL AUTO_INCREMENT,
  `campaign_id` INT NOT NULL,
  `keywords` VARCHAR(300) NOT NULL,
  `title` VARCHAR(300) NOT NULL,
  `price` DOUBLE NOT NULL,
  `thumbnail` MEDIUMTEXT NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `detail_url` MEDIUMTEXT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `bid_price` DOUBLE NULL,
  `pClick` DOUBLE NULL,
  PRIMARY KEY (`ad_id`),
  INDEX `fk_Ad_Campaign_idx` (`campaign_id` ASC),
  CONSTRAINT `fk_Ad_Campaign`
    FOREIGN KEY (`campaign_id`)
    REFERENCES `AdSearchDB`.`campaign` (`campaign_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
